/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuildAiAgentsRouteImport } from './routes/build-ai-agents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as BuildsWeekRouteImport } from './routes/builds.$week'
import { Route as AdminUtmLinksIndexRouteImport } from './routes/admin/utm-links.index'
import { Route as AdminUtmLinksShortCodeRouteImport } from './routes/admin/utm-links.$shortCode'
import { Route as AdminUtmLinksNewRouteImport } from './routes/admin/utm-links.new'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiRazorpayCreateOrderRouteImport } from './routes/api/razorpay/create-order'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api/razorpay/verify'
import { Route as ApiPublicRShortCodeRouteImport } from './routes/api/public/r.$shortCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildAiAgentsRoute = BuildAiAgentsRouteImport.update({
  id: '/build-ai-agents',
  path: '/build-ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsWeekRoute = BuildsWeekRouteImport.update({
  id: '/builds/$week',
  path: '/builds/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUtmLinksIndexRoute = AdminUtmLinksIndexRouteImport.update({
  id: '/utm-links/',
  path: '/utm-links/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtmLinksShortCodeRoute = AdminUtmLinksShortCodeRouteImport.update({
  id: '/utm-links/$shortCode',
  path: '/utm-links/$shortCode',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtmLinksNewRoute = AdminUtmLinksNewRouteImport.update({
  id: '/utm-links/new',
  path: '/utm-links/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRazorpayCreateOrderRoute = ApiRazorpayCreateOrderRouteImport.update({
  id: '/api/razorpay/create-order',
  path: '/api/razorpay/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRShortCodeRoute = ApiPublicRShortCodeRouteImport.update({
  id: '/api/public/r/$shortCode',
  path: '/api/public/r/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/build-ai-agents': typeof BuildAiAgentsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/builds/$week': typeof BuildsWeekRoute
  '/builds/': typeof BuildsIndexRoute
  '/admin/utm-links/$shortCode': typeof AdminUtmLinksShortCodeRoute
  '/admin/utm-links/new': typeof AdminUtmLinksNewRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/admin/utm-links/': typeof AdminUtmLinksIndexRoute
  '/api/public/r/$shortCode': typeof ApiPublicRShortCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/build-ai-agents': typeof BuildAiAgentsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/builds/$week': typeof BuildsWeekRoute
  '/builds': typeof BuildsIndexRoute
  '/admin/utm-links/$shortCode': typeof AdminUtmLinksShortCodeRoute
  '/admin/utm-links/new': typeof AdminUtmLinksNewRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/admin/utm-links': typeof AdminUtmLinksIndexRoute
  '/api/public/r/$shortCode': typeof ApiPublicRShortCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/build-ai-agents': typeof BuildAiAgentsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/login': typeof AdminLoginRoute
  '/builds/$week': typeof BuildsWeekRoute
  '/builds/': typeof BuildsIndexRoute
  '/admin/utm-links/$shortCode': typeof AdminUtmLinksShortCodeRoute
  '/admin/utm-links/new': typeof AdminUtmLinksNewRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/admin/utm-links/': typeof AdminUtmLinksIndexRoute
  '/api/public/r/$shortCode': typeof ApiPublicRShortCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/build-ai-agents'
    | '/contact'
    | '/faq'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/login'
    | '/builds/$week'
    | '/builds/'
    | '/admin/utm-links/$shortCode'
    | '/admin/utm-links/new'
    | '/api/public/events'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
    | '/admin/utm-links/'
    | '/api/public/r/$shortCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/build-ai-agents'
    | '/contact'
    | '/faq'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/login'
    | '/builds/$week'
    | '/builds'
    | '/admin/utm-links/$shortCode'
    | '/admin/utm-links/new'
    | '/api/public/events'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
    | '/admin/utm-links'
    | '/api/public/r/$shortCode'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/build-ai-agents'
    | '/contact'
    | '/faq'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/admin/analytics'
    | '/admin/login'
    | '/builds/$week'
    | '/builds/'
    | '/admin/utm-links/$shortCode'
    | '/admin/utm-links/new'
    | '/api/public/events'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
    | '/admin/utm-links/'
    | '/api/public/r/$shortCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuildAiAgentsRoute: typeof BuildAiAgentsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JoinRoute: typeof JoinRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  BuildsWeekRoute: typeof BuildsWeekRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiRazorpayCreateOrderRoute: typeof ApiRazorpayCreateOrderRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
  ApiPublicRShortCodeRoute: typeof ApiPublicRShortCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-ai-agents': {
      id: '/build-ai-agents'
      path: '/build-ai-agents'
      fullPath: '/build-ai-agents'
      preLoaderRoute: typeof BuildAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$week': {
      id: '/builds/$week'
      path: '/builds/$week'
      fullPath: '/builds/$week'
      preLoaderRoute: typeof BuildsWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/utm-links/': {
      id: '/admin/utm-links/'
      path: '/utm-links'
      fullPath: '/admin/utm-links/'
      preLoaderRoute: typeof AdminUtmLinksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utm-links/$shortCode': {
      id: '/admin/utm-links/$shortCode'
      path: '/utm-links/$shortCode'
      fullPath: '/admin/utm-links/$shortCode'
      preLoaderRoute: typeof AdminUtmLinksShortCodeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utm-links/new': {
      id: '/admin/utm-links/new'
      path: '/utm-links/new'
      fullPath: '/admin/utm-links/new'
      preLoaderRoute: typeof AdminUtmLinksNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/create-order': {
      id: '/api/razorpay/create-order'
      path: '/api/razorpay/create-order'
      fullPath: '/api/razorpay/create-order'
      preLoaderRoute: typeof ApiRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/r/$shortCode': {
      id: '/api/public/r/$shortCode'
      path: '/api/public/r/$shortCode'
      fullPath: '/api/public/r/$shortCode'
      preLoaderRoute: typeof ApiPublicRShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUtmLinksShortCodeRoute: typeof AdminUtmLinksShortCodeRoute
  AdminUtmLinksNewRoute: typeof AdminUtmLinksNewRoute
  AdminUtmLinksIndexRoute: typeof AdminUtmLinksIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUtmLinksShortCodeRoute: AdminUtmLinksShortCodeRoute,
  AdminUtmLinksNewRoute: AdminUtmLinksNewRoute,
  AdminUtmLinksIndexRoute: AdminUtmLinksIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BuildAiAgentsRoute: BuildAiAgentsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JoinRoute: JoinRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  BuildsWeekRoute: BuildsWeekRoute,
  BuildsIndexRoute: BuildsIndexRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiRazorpayCreateOrderRoute: ApiRazorpayCreateOrderRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
  ApiPublicRShortCodeRoute: ApiPublicRShortCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
