/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as BuildsWeekRouteImport } from './routes/builds.$week'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiRazorpayCreateOrderRouteImport } from './routes/api/razorpay/create-order'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api/razorpay/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsWeekRoute = BuildsWeekRouteImport.update({
  id: '/builds/$week',
  path: '/builds/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRazorpayCreateOrderRoute = ApiRazorpayCreateOrderRouteImport.update({
  id: '/api/razorpay/create-order',
  path: '/api/razorpay/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/builds/$week': typeof BuildsWeekRoute
  '/builds/': typeof BuildsIndexRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/builds/$week': typeof BuildsWeekRoute
  '/builds': typeof BuildsIndexRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/join': typeof JoinRoute
  '/membership': typeof MembershipRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/builds/$week': typeof BuildsWeekRoute
  '/builds/': typeof BuildsIndexRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/builds/$week'
    | '/builds/'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/builds/$week'
    | '/builds'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/join'
    | '/membership'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/builds/$week'
    | '/builds/'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JoinRoute: typeof JoinRoute
  MembershipRoute: typeof MembershipRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  BuildsWeekRoute: typeof BuildsWeekRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiRazorpayCreateOrderRoute: typeof ApiRazorpayCreateOrderRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$week': {
      id: '/builds/$week'
      path: '/builds/$week'
      fullPath: '/builds/$week'
      preLoaderRoute: typeof BuildsWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/create-order': {
      id: '/api/razorpay/create-order'
      path: '/api/razorpay/create-order'
      fullPath: '/api/razorpay/create-order'
      preLoaderRoute: typeof ApiRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JoinRoute: JoinRoute,
  MembershipRoute: MembershipRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  BuildsWeekRoute: BuildsWeekRoute,
  BuildsIndexRoute: BuildsIndexRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiRazorpayCreateOrderRoute: ApiRazorpayCreateOrderRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
